---
- name: Create user accounts and add to the sudo group
  loop: "{{ users }}"
  user:
    name: "{{ item.name }}"
    state: present
    create_home: yes
    shell: /bin/bash
    groups: sudo
    append: yes
  become: true

- name: Set up authorized_keys for the user accounts
  loop: "{{ users }}"
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  become: true

- name: Setup 'iac' user to run Ansible
  lineinfile:
    path: /etc/sudoers.d/iac
    line: "iac ALL=(ALL) NOPASSWD:ALL"
    create: yes
    validate: "visudo -cf %s"
  when: "'iac' in users | map(attribute='name')"
  become: true